export const ProductData = [
    {
        ProductNo: "001",
        ProductName: "SKIN 1004",
        ProductImage: ["/images/phan_nuoc.png", "/images/phan_nuoc.png"],
        ProductDescription:
            "SKIN1004 Madagascar Centella Hyalu-Cica Water-Fit Sun Serum 50ml",
        ProductVote: "4.6",
        ProductPrice: "350.000vnd",
        ProductSaledPrice: "250.000vnd",
        ProductInventory: "10",
        ProductCapacity: "210ml",
        ProductPromotion: "30%",
        ProductType: "cosmetic",
        ProductBrand: "Instree",
        ProductIngredient: "natural",
        ProductTag: "on sale",
        ProductReview: "good",
    },
    {
        ProductNo: "002",
        ProductName: "Instree",
        ProductImage: ["/images/phan_nuoc.png"],
        ProductDescription:
            "Isntree Hyaluronic Acid Watery Sun Gel Double Set (50mL+50mL)",
        ProductVote: "4.2",
        ProductPrice: "350.000vnd",
        ProductSaledPrice: "250.000vnd",
        ProductInventory: "10",
        ProductCapacity: "210ml",
        ProductPromotion: "30%",
        ProductType: "cosmetic",
        ProductBrand: "Instree",
        ProductIngredient: "natural",
        ProductTag: "on sale",
        ProductReview: "good",
    },
    {
        ProductNo: "003",
        ProductName: "AESTURA",
        ProductImage: ["/images/phan_nuoc.png"],
        ProductDescription: "AESTURA Atobarrier 365 Cream 80mL Double Set",
        ProductVote: "4.6",
        ProductPrice: "350.000vnd",
        ProductSaledPrice: "250.000vnd",
        ProductInventory: "10",
        ProductCapacity: "210ml",
        ProductPromotion: "30%",
        ProductType: "cosmetic",
        ProductBrand: "Instree",
        ProductIngredient: "natural",
        ProductTag: "on sale",
        ProductReview: "good",
    },
    {
        ProductNo: "004",
        ProductName: "Real Barrier",
        ProductImage: ["/images/phan_nuoc.png"],
        ProductDescription: "Real Barrier Cream Cleaning Foam 120ml Duo Pack",
        ProductVote: "4.6",
        ProductPrice: "350.000vnd",
        ProductSaledPrice: "250.000vnd",
        ProductInventory: "10",
        ProductCapacity: "210ml",
        ProductPromotion: "30%",
        ProductType: "cosmetic",
        ProductBrand: "Instree",
        ProductIngredient: "natural",
        ProductTag: "on sale",
        ProductReview: "good",
    },
    {
        ProductNo: "005",
        ProductName: "ROUND LAB",
        ProductImage: ["/images/phan_nuoc.png"],
        ProductDescription:
            "ROUND LAB Birch Juice Moisturizing Ampoule 50ml Special Set (+Cream 20ml)",
        ProductVote: "4.6",
        ProductPrice: "350.000vnd",
        ProductSaledPrice: "250.000vnd",
        ProductInventory: "10",
        ProductCapacity: "210ml",
        ProductPromotion: "30%",
        ProductType: "cosmetic",
        ProductBrand: "Instree",
        ProductIngredient: "natural",
        ProductTag: "on sale",
        ProductReview: "good",
    },
];
