export const UserInforData = [
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID002",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID003",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID004",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID005",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID006",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID006",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID008",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
    {
        userID: "UID009",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
        userEmail: "wade.warren@example.com",
        userAddress: "3/2, phường Xuân Khánh, quận Ninh Kiều, TP. Cần Thơ",
    },
];
