export const UserInfor = [
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
    {
        userID: "UID001",
        userName: "Esthera Jackson",
        userPhoneNumber: "0958263253",
        userGender: "Nam",
        userAge: 21,
    },
];
